import environ
import requests
from http import HTTPStatus

env = environ.Env()
environ.Env.read_env()


DB_NAME = env("DB_NAME")
DB_USER = env("DB_USER")
DB_PASSWORD = env("DB_PASSWORD")
DB_HOST = env("DB_HOST")
DB_PORT = env("DB_PORT")

NONOGRAM_SERVER_PROTOCOL = env("NONOGRAM_SERVER_PROTOCOL")
NONOGRAM_SERVER_HOST = env("NONOGRAM_SERVER_HOST")
NONOGRAM_SERVER_PORT = env("NONOGRAM_SERVER_PORT")

API_SERVER_PROTOCOL = env("NONOGRAM_SERVER_PROTOCOL")
API_SERVER_HOST = env("API_SERVER_HOST")
API_SERVER_PORT = env("NONOGRAM_SERVER_PORT")

NONOGRAM_SERVER_URL = f"{NONOGRAM_SERVER_PROTOCOL}://{NONOGRAM_SERVER_HOST}:{NONOGRAM_SERVER_PORT}"
API_SERVER_URL = f"{API_SERVER_PROTOCOL}://{API_SERVER_HOST}:{API_SERVER_PORT}"


def test(load_servers):
    response = requests.get(f"{NONOGRAM_SERVER_URL}/healthcheck")
    assert response.status_code == HTTPStatus.OK