FROM python:3.10-slim-bullseye

COPY pyproject.toml pyproject.toml
COPY src/ApiServer /ApiServer

RUN pip install poetry
ENV PATH="${PATH}:/root/.local/bin"

RUN poetry install

WORKDIR /ApiServer

ENTRYPOINT ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]