FROM python:3.10-slim-bullseye

COPY pyproject.toml pyproject.toml
COPY src/ApiServer /ApiServer

RUN pip install poetry
ENV PATH="${PATH}:/root/.local/bin"

RUN poetry export -f requirements.txt -o requirements.txt --without-hashes
RUN pip install -r requirements.txt

WORKDIR /ApiServer

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]