FROM python:3.10-slim-bullseye

RUN apt-get update && apt-get install -y curl
RUN pip install --upgrade pip

COPY pyproject.toml pyproject.toml

RUN pip install poetry
ENV PATH="${PATH}:/root/.local/bin"

RUN poetry export -f requirements.txt -o requirements.txt --without-hashes
RUN pip install -r requirements.txt