FROM python:3.10-slim-bullseye

RUN apt-get update && apt-get install -y curl

COPY pyproject.toml pyproject.toml
COPY src/NonogramServer /src/NonogramServer
COPY src/utils.py /src/utils.py

RUN pip install poetry
ENV PATH="${PATH}:/root/.local/bin"

RUN poetry export -f requirements.txt -o requirements.txt --without-hashes
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "src/NonogramServer/manage.py", "runserver", "0.0.0.0:8000"]